name: Build and Test

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Checkout pcre
        uses: actions/checkout@v2
        with:
          path: pcre

      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Ensure everything is formatted
        run: v fmt -verify pcre/

      - name: Run tests
        run: v test pcre/

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Checkout pcre
        uses: actions/checkout@v2
        with:
          path: pcre

      - name: Build V
        run: |
          make
          ./v symlink

      - name: Ensure everything is formatted
        run: v fmt -verify pcre/

      - name: Run tests
        run: v test pcre/

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Checkout pcre
        uses: actions/checkout@v2
        with:
          path: pcre

      - name: Build V
        run: |
          ./make.bat -gcc

      - name: Ensure everything is formatted
        run: v fmt -verify pcre/

      - name: Run tests
        run: v test pcre/
