name: Build and Test

on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
        path: v

    - name: Checkout pcre
      uses: actions/checkout@v2
      with:
        path: pcre

    - name: Build V
      run: cd v && make && sudo ./v symlink && cd -

    - name: V doctor
      run: v doctor

    - name: Symlink pcre to ~/.vmodules
      run: ln -s $(pwd)/pcre ~/.vmodules/pcre

    - name: Ensure everything is formatted
      run: v fmt -verify pcre/

    - name: Run tests
      run: v test pcre/

    - name: Build example
      run: v pcre/examples/hello.v

    - name: Build example-prod
      run: v -prod pcre/examples/hello.v
