name: Build and Test

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
        path: v

    - name: Checkout Coreutils
      uses: actions/checkout@v2
      with:
        path: pcre

    - name: Install libpcre3-dev package
      run: sudo apt-get install --quiet -y libpcre3-dev

    - name: Build V
      run: cd v && make && sudo ./v symlink && cd -

    - name: V doctor
      run: v doctor

    - name: Symlink pcre to ~/.vmodules
      run: ln -s $(pwd)/pcre ~/.vmodules/pcre

    - name: Ensure everything is formatted
      run: v fmt -verify pcre/

    - name: Run tests
      run: v test pcre/

    - name: Build example
      run: v -cstrict pcre/examples/hello.v

    - name: Build example with -prod
      run: v -cc gcc -cstrict -prod pcre/examples/hello.v
